name: Deploy Examples to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build-examples

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./example/bundle

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
